---
title:
- type: main
  text: The Kelsey Papers
- type: subtitle
  text: With an introduction by Arthur G. Doughty and Chester Martin
- type: extended
  text: The Public Archives of Canada and The Public Record Office of Northern Ireland, 1929
creator:
- role: author
  text: Henry Kelsey
rights: © 2022 Public domain
...
